TENSE_LIST = ['pres',
              'pret_perf_comp',
              'pret_imp',
              'pret_plus',
              'pret_perf_simp',
              'pret_ant',
              'fut',
              'fut_perf',
              'cond',
              'cond_perf',
              'sub_pres',
              'sub_pret_perf',
              'sub_pret_imp1',
              'pret_plus1'
              'sub_pret_imp2',
              'pret_plus2'
              'sub_fut',
              'sub_fut_perf']


INFINITIVES = ['vencer', 'esparcir', 'dirigir', 'delinquir', 'distinguir', 'parecer', 'conocer', 'nacer', 'lucir',
               'concluir', 'calentar', 'perder', 'contar', 'mover', 'moverse', 'jugar', 'discernir', 'sentir',
               'dormir', 'pedir', 'dar', 'ir', 'ser','estar', 'saber', 'ver', 'Caber', 'haber', 'poner', 'valer',
               'salir', 'venir', 'tener', 'caer', 'traer', 'oir', 'hacer', 'decir', 'casarse', 'depender', 'pretender',
               'abrir', 'almorzar', 'deber', 'corregir', 'costar', 'devolver', 'seguir', 'caber', 'volver', 'llover',
               'repasar', 'poder', 'tomar', 'sonar', 'colgar', 'comprar', 'llegar', 'alquilar', 'llenar', 'conducir',
               'necesitar', 'esperar', 'empezar', 'fingir', 'encantar', 'preguntar', 'soler', 'confirmar', 'agradecer',
               'acordarse', 'hervir', 'lavar', 'soñar', 'morder', 'callar', 'prestar', 'conseguir', 'acabar', 'acercar',
               'tratar', 'gastar', 'cargar', 'encontrar', 'sacar', 'responder', 'acelerar', 'frener', 'engordar',
               'adelgazar', 'sanar', 'enfermar', 'guiar', 'luchar', 'vestir', 'enviar', 'crecer', 'temer', 'alcanzar',
               'mitigar', 'confesar', 'subyugar', 'aproximarse', 'cualquier', 'lamer', 'discutir', 'romper', 'saltar',
               'acariciar', 'cortar', 'elegir', 'afeitarse', 'cruzar', 'desear', 'probar', 'esconder', 'irse',
               'llevarse', 'burlarse', 'ladrar', 'aburrir', 'fastidiar', 'molestar', 'extrañarse', 'entristacer',
               'alegrar', 'importar', 'apetecer', 'quejarse', 'notar', 'aplaudir', 'buscar', 'dudar', 'respetar',
               'esperar', 'asistir', 'ayudar', 'quemar', 'compartir', 'separar', 'dejar', 'mostrar', 'repartir',
               'ocurrir', 'apagar', 'aparecer', 'descubrir', 'aconsejar', 'mejorar', 'sufrir', 'lamentar', 'mandar',
               'ordenar', 'guardar', 'olvidar', 'avisar', 'detener', 'traicionar', 'aprovechar', 'enfrentar',
               'despedirse', 'abajar', 'derrochar', 'relajar', 'cuidar', 'prever', 'curar', 'destacar', 'exponer',
               'suponer', 'aislar', 'usar', 'entregar', 'ajustar', 'exprimir', 'expresar', 'viajar', 'explicar',
               'fallar', 'dificultar', 'envolver', 'extinguir', 'infligir', 'tropezar', 'apaciguar', 'trocar',
               'proteger', 'ejercer', 'desguazar', 'restituir', 'volcar', 'soplar', 'pasmar', 'rumiar', 'comprobar',
               'tumbar', 'sumar', 'esbozar', 'horrorizar', 'perseguir', 'descargar', 'aplazar', 'contener', 'robar',
               'despedir']